2023-01-01 16:04:37,363 (7ff019dbd808) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 629d580 (Thu Dec 08 08:44:59 UTC 2022)
2023-01-01 16:04:37,364 (7ff019dbd808) :  DEBUG (core:361) - Using the elevated policy
2023-01-01 16:04:37,364 (7ff019dbd808) :  DEBUG (core:450) - Starting runtime component.
2023-01-01 16:04:37,365 (7ff019dbd808) :  DEBUG (core:450) - Starting caching component.
2023-01-01 16:04:37,365 (7ff019dbd808) :  DEBUG (core:450) - Starting data component.
2023-01-01 16:04:37,365 (7ff019dbd808) :  DEBUG (core:450) - Starting networking component.
2023-01-01 16:04:37,365 (7ff019dbd808) :  DEBUG (networking:265) - No cookie jar found
2023-01-01 16:04:37,366 (7ff019dbd808) :  DEBUG (networking:428) - Setting the default network timeout to 20.0
2023-01-01 16:04:37,366 (7ff019dbd808) :  DEBUG (core:450) - Starting localization component.
2023-01-01 16:04:37,366 (7ff019dbd808) :  INFO (localization:409) - Setting the default locale to en-us
2023-01-01 16:04:37,366 (7ff019dbd808) :  DEBUG (core:450) - Starting messaging component.
2023-01-01 16:04:37,367 (7ff019dbd808) :  DEBUG (core:450) - Starting debugging component.
2023-01-01 16:04:37,367 (7ff019dbd808) :  DEBUG (core:450) - Starting services component.
2023-01-01 16:04:37,367 (7ff019dbd808) :  DEBUG (core:450) - Starting myplex component.
2023-01-01 16:04:37,367 (7ff019dbd808) :  DEBUG (core:450) - Starting notifications component.
2023-01-01 16:04:37,368 (7ff016bd3b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2023-01-01 16:04:37,467 (7ff019dbd808) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2023-01-01 16:04:37,470 (7ff019dbd808) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-01-01 16:04:37,474 (7ff019dbd808) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-01-01 16:04:37,475 (7ff019dbd808) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 242, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 220, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2023-01-01 16:04:37,481 (7ff0169d1b38) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2023-01-01 16:04:37,481 (7ff019dbd808) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2023-01-01 16:04:37,482 (7ff0169d1b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2023-01-01 16:04:37,483 (7ff019dbd808) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2023-01-01 16:04:37,483 (7ff01698bb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400'
2023-01-01 16:04:37,483 (7ff019dbd808) :  DEBUG (core:150) - Finished starting framework core
2023-01-01 16:04:37,484 (7ff019dbd808) :  DEBUG (core:560) - Loading plug-in code
2023-01-01 16:04:37,582 (7ff0169d1b38) :  DEBUG (services:362) - Loaded services
2023-01-01 16:04:37,607 (7ff01698bb38) :  DEBUG (core:538) - Machine identifier is fb685177d8f6bb83de49fedfebd2ed47642b5881
2023-01-01 16:04:37,623 (7ff01698bb38) :  DEBUG (core:539) - Server version is 1.30.0.6486-629d58034
2023-01-01 16:04:37,630 (7ff0169aeb38) :  DEBUG (services:438) - No shared code to load
2023-01-01 16:04:37,837 (7ff019dbd808) :  DEBUG (core:566) - Finished loading plug-in code
2023-01-01 16:04:37,838 (7ff019dbd808) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2023-01-01 16:04:37,838 (7ff019dbd808) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2023-01-01 16:04:37,839 (7ff019dbd808) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2023-01-01 16:04:56,890 (7ff019dbd808) :  INFO (core:611) - Started plug-in
2023-01-01 16:04:56,890 (7ff019dbd808) :  DEBUG (socketinterface:160) - Starting socket server
2023-01-01 16:04:56,891 (7ff019dbd808) :  DEBUG (runtime:1117) - Created a thread named 'start'
2023-01-01 16:04:56,891 (7ff019dbd808) :  INFO (socketinterface:184) - Socket server started on port 38385
2023-01-01 16:04:56,891 (7ff019dbd808) :  INFO (pipeinterface:25) - Entering run loop
2023-01-01 16:04:56,891 (7ff019dbd808) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2023-01-01 16:04:56,892 (7ff019dbd808) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2023-01-01 16:04:56,893 (7ff019dbd808) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2023-01-01 16:04:56,901 (7ff015f31b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 16:04:56,903 (7ff015f0eb38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 16:04:56,915 (7ff015f31b38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-01-01 16:04:56,915 (7ff015f31b38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 16:04:56,916 (7ff015f31b38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-01-01 16:04:56,916 (7ff015f0eb38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-01-01 16:04:56,916 (7ff015f31b38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2023-01-01 16:04:56,917 (7ff015f0eb38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 16:04:56,917 (7ff015f0eb38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-01-01 16:04:56,918 (7ff015f0eb38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
